// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: self.data.format/ProtobufData.proto

package self.data.format.protobuf;

public final class ProtobufDataOuterClass {
  private ProtobufDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:self.data.format.ProtobufData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
     */
    ProtobufDataOuterClass.ProtobufData.Type getType();

    /**
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
     */
    ProtobufDataOuterClass.ProtobufData.State getState();

    /**
     * <code>optional string uid = 4;</code>
     */
    boolean hasUid();
    /**
     * <code>optional string uid = 4;</code>
     */
    java.lang.String getUid();
    /**
     * <code>optional string uid = 4;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData>
        getListList();
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    ProtobufDataOuterClass.ProtobufData.SensorData getList(int index);
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    int getListCount();
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    java.util.List<? extends ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder>
        getListOrBuilderList();
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code self.data.format.ProtobufData}
   */
  public  static final class ProtobufData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:self.data.format.ProtobufData)
      ProtobufDataOrBuilder {
    // Use ProtobufData.newBuilder() to construct.
    private ProtobufData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufData() {
      type_ = 1;
      timestamp_ = 0L;
      state_ = 1;
      uid_ = "";
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtobufData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ProtobufDataOuterClass.ProtobufData.Type value = ProtobufDataOuterClass.ProtobufData.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              ProtobufDataOuterClass.ProtobufData.State value = ProtobufDataOuterClass.ProtobufData.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                state_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              uid_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                list_ = new java.util.ArrayList<ProtobufDataOuterClass.ProtobufData.SensorData>();
                mutable_bitField0_ |= 0x00000010;
              }
              list_.add(
                  input.readMessage(ProtobufDataOuterClass.ProtobufData.SensorData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufDataOuterClass.ProtobufData.class, ProtobufDataOuterClass.ProtobufData.Builder.class);
    }

    /**
     * Protobuf enum {@code self.data.format.ProtobufData.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 1;</code>
       */
      PING(1),
      /**
       * <code>PONG = 2;</code>
       */
      PONG(2),
      /**
       * <code>UPLOAD = 3;</code>
       */
      UPLOAD(3),
      /**
       * <code>RSP_UPLOAD = 4;</code>
       */
      RSP_UPLOAD(4),
      /**
       * <code>SIGNUP = 5;</code>
       */
      SIGNUP(5),
      /**
       * <code>RSP_SIGNUP = 6;</code>
       */
      RSP_SIGNUP(6),
      /**
       * <code>SIGNIN = 7;</code>
       */
      SIGNIN(7),
      /**
       * <code>RSP_SIGNIN = 8;</code>
       */
      RSP_SIGNIN(8),
      ;

      /**
       * <code>PING = 1;</code>
       */
      public static final int PING_VALUE = 1;
      /**
       * <code>PONG = 2;</code>
       */
      public static final int PONG_VALUE = 2;
      /**
       * <code>UPLOAD = 3;</code>
       */
      public static final int UPLOAD_VALUE = 3;
      /**
       * <code>RSP_UPLOAD = 4;</code>
       */
      public static final int RSP_UPLOAD_VALUE = 4;
      /**
       * <code>SIGNUP = 5;</code>
       */
      public static final int SIGNUP_VALUE = 5;
      /**
       * <code>RSP_SIGNUP = 6;</code>
       */
      public static final int RSP_SIGNUP_VALUE = 6;
      /**
       * <code>SIGNIN = 7;</code>
       */
      public static final int SIGNIN_VALUE = 7;
      /**
       * <code>RSP_SIGNIN = 8;</code>
       */
      public static final int RSP_SIGNIN_VALUE = 8;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 1: return PING;
          case 2: return PONG;
          case 3: return UPLOAD;
          case 4: return RSP_UPLOAD;
          case 5: return SIGNUP;
          case 6: return RSP_SIGNUP;
          case 7: return SIGNIN;
          case 8: return RSP_SIGNIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtobufDataOuterClass.ProtobufData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:self.data.format.ProtobufData.Type)
    }

    /**
     * Protobuf enum {@code self.data.format.ProtobufData.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(1),
      /**
       * <code>ERROR = -1;</code>
       */
      ERROR(-1),
      ;

      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>ERROR = -1;</code>
       */
      public static final int ERROR_VALUE = -1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      public static State forNumber(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case -1: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtobufDataOuterClass.ProtobufData.getDescriptor().getEnumTypes().get(1);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:self.data.format.ProtobufData.State)
    }

    /**
     * Protobuf enum {@code self.data.format.ProtobufData.Sensor}
     */
    public enum Sensor
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACCELERATION = 1;</code>
       */
      ACCELERATION(1),
      /**
       * <code>MAGNETISM = 2;</code>
       */
      MAGNETISM(2),
      ;

      /**
       * <code>ACCELERATION = 1;</code>
       */
      public static final int ACCELERATION_VALUE = 1;
      /**
       * <code>MAGNETISM = 2;</code>
       */
      public static final int MAGNETISM_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sensor valueOf(int value) {
        return forNumber(value);
      }

      public static Sensor forNumber(int value) {
        switch (value) {
          case 1: return ACCELERATION;
          case 2: return MAGNETISM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sensor>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sensor> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sensor>() {
              public Sensor findValueByNumber(int number) {
                return Sensor.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtobufDataOuterClass.ProtobufData.getDescriptor().getEnumTypes().get(2);
      }

      private static final Sensor[] VALUES = values();

      public static Sensor valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sensor(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:self.data.format.ProtobufData.Sensor)
    }

    public interface SensorDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:self.data.format.ProtobufData.SensorData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
       */
      boolean hasSensor();
      /**
       * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
       */
      ProtobufDataOuterClass.ProtobufData.Sensor getSensor();

      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      java.util.List<java.lang.Long> getTimestampList();
      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      int getTimestampCount();
      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      long getTimestamp(int index);

      /**
       * <code>repeated double x = 3;</code>
       */
      java.util.List<java.lang.Double> getXList();
      /**
       * <code>repeated double x = 3;</code>
       */
      int getXCount();
      /**
       * <code>repeated double x = 3;</code>
       */
      double getX(int index);

      /**
       * <code>repeated double y = 4;</code>
       */
      java.util.List<java.lang.Double> getYList();
      /**
       * <code>repeated double y = 4;</code>
       */
      int getYCount();
      /**
       * <code>repeated double y = 4;</code>
       */
      double getY(int index);

      /**
       * <code>repeated double z = 5;</code>
       */
      java.util.List<java.lang.Double> getZList();
      /**
       * <code>repeated double z = 5;</code>
       */
      int getZCount();
      /**
       * <code>repeated double z = 5;</code>
       */
      double getZ(int index);
    }
    /**
     * Protobuf type {@code self.data.format.ProtobufData.SensorData}
     */
    public  static final class SensorData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:self.data.format.ProtobufData.SensorData)
        SensorDataOrBuilder {
      // Use SensorData.newBuilder() to construct.
      private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private SensorData() {
        sensor_ = 1;
        timestamp_ = java.util.Collections.emptyList();
        x_ = java.util.Collections.emptyList();
        y_ = java.util.Collections.emptyList();
        z_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SensorData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                ProtobufDataOuterClass.ProtobufData.Sensor value = ProtobufDataOuterClass.ProtobufData.Sensor.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  sensor_ = rawValue;
                }
                break;
              }
              case 16: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  timestamp_ = new java.util.ArrayList<java.lang.Long>();
                  mutable_bitField0_ |= 0x00000002;
                }
                timestamp_.add(input.readInt64());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                  timestamp_ = new java.util.ArrayList<java.lang.Long>();
                  mutable_bitField0_ |= 0x00000002;
                }
                while (input.getBytesUntilLimit() > 0) {
                  timestamp_.add(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
              case 25: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  x_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000004;
                }
                x_.add(input.readDouble());
                break;
              }
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                  x_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000004;
                }
                while (input.getBytesUntilLimit() > 0) {
                  x_.add(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
              case 33: {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  y_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000008;
                }
                y_.add(input.readDouble());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                  y_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000008;
                }
                while (input.getBytesUntilLimit() > 0) {
                  y_.add(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
              case 41: {
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                  z_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000010;
                }
                z_.add(input.readDouble());
                break;
              }
              case 42: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                  z_ = new java.util.ArrayList<java.lang.Double>();
                  mutable_bitField0_ |= 0x00000010;
                }
                while (input.getBytesUntilLimit() > 0) {
                  z_.add(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            timestamp_ = java.util.Collections.unmodifiableList(timestamp_);
          }
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            x_ = java.util.Collections.unmodifiableList(x_);
          }
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            y_ = java.util.Collections.unmodifiableList(y_);
          }
          if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
            z_ = java.util.Collections.unmodifiableList(z_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_SensorData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufDataOuterClass.ProtobufData.SensorData.class, ProtobufDataOuterClass.ProtobufData.SensorData.Builder.class);
      }

      private int bitField0_;
      public static final int SENSOR_FIELD_NUMBER = 1;
      private int sensor_;
      /**
       * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
       */
      public boolean hasSensor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.Sensor getSensor() {
        ProtobufDataOuterClass.ProtobufData.Sensor result = ProtobufDataOuterClass.ProtobufData.Sensor.valueOf(sensor_);
        return result == null ? ProtobufDataOuterClass.ProtobufData.Sensor.ACCELERATION : result;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 2;
      private java.util.List<java.lang.Long> timestamp_;
      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getTimestampList() {
        return timestamp_;
      }
      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      public int getTimestampCount() {
        return timestamp_.size();
      }
      /**
       * <code>repeated int64 timestamp = 2;</code>
       */
      public long getTimestamp(int index) {
        return timestamp_.get(index);
      }

      public static final int X_FIELD_NUMBER = 3;
      private java.util.List<java.lang.Double> x_;
      /**
       * <code>repeated double x = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getXList() {
        return x_;
      }
      /**
       * <code>repeated double x = 3;</code>
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated double x = 3;</code>
       */
      public double getX(int index) {
        return x_.get(index);
      }

      public static final int Y_FIELD_NUMBER = 4;
      private java.util.List<java.lang.Double> y_;
      /**
       * <code>repeated double y = 4;</code>
       */
      public java.util.List<java.lang.Double>
          getYList() {
        return y_;
      }
      /**
       * <code>repeated double y = 4;</code>
       */
      public int getYCount() {
        return y_.size();
      }
      /**
       * <code>repeated double y = 4;</code>
       */
      public double getY(int index) {
        return y_.get(index);
      }

      public static final int Z_FIELD_NUMBER = 5;
      private java.util.List<java.lang.Double> z_;
      /**
       * <code>repeated double z = 5;</code>
       */
      public java.util.List<java.lang.Double>
          getZList() {
        return z_;
      }
      /**
       * <code>repeated double z = 5;</code>
       */
      public int getZCount() {
        return z_.size();
      }
      /**
       * <code>repeated double z = 5;</code>
       */
      public double getZ(int index) {
        return z_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasSensor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, sensor_);
        }
        for (int i = 0; i < timestamp_.size(); i++) {
          output.writeInt64(2, timestamp_.get(i));
        }
        for (int i = 0; i < x_.size(); i++) {
          output.writeDouble(3, x_.get(i));
        }
        for (int i = 0; i < y_.size(); i++) {
          output.writeDouble(4, y_.get(i));
        }
        for (int i = 0; i < z_.size(); i++) {
          output.writeDouble(5, z_.get(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, sensor_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < timestamp_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt64SizeNoTag(timestamp_.get(i));
          }
          size += dataSize;
          size += 1 * getTimestampList().size();
        }
        {
          int dataSize = 0;
          dataSize = 8 * getXList().size();
          size += dataSize;
          size += 1 * getXList().size();
        }
        {
          int dataSize = 0;
          dataSize = 8 * getYList().size();
          size += dataSize;
          size += 1 * getYList().size();
        }
        {
          int dataSize = 0;
          dataSize = 8 * getZList().size();
          size += dataSize;
          size += 1 * getZList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtobufDataOuterClass.ProtobufData.SensorData)) {
          return super.equals(obj);
        }
        ProtobufDataOuterClass.ProtobufData.SensorData other = (ProtobufDataOuterClass.ProtobufData.SensorData) obj;

        boolean result = true;
        result = result && (hasSensor() == other.hasSensor());
        if (hasSensor()) {
          result = result && sensor_ == other.sensor_;
        }
        result = result && getTimestampList()
            .equals(other.getTimestampList());
        result = result && getXList()
            .equals(other.getXList());
        result = result && getYList()
            .equals(other.getYList());
        result = result && getZList()
            .equals(other.getZList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasSensor()) {
          hash = (37 * hash) + SENSOR_FIELD_NUMBER;
          hash = (53 * hash) + sensor_;
        }
        if (getTimestampCount() > 0) {
          hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
          hash = (53 * hash) + getTimestampList().hashCode();
        }
        if (getXCount() > 0) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + getXList().hashCode();
        }
        if (getYCount() > 0) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + getYList().hashCode();
        }
        if (getZCount() > 0) {
          hash = (37 * hash) + Z_FIELD_NUMBER;
          hash = (53 * hash) + getZList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtobufDataOuterClass.ProtobufData.SensorData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtobufDataOuterClass.ProtobufData.SensorData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code self.data.format.ProtobufData.SensorData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:self.data.format.ProtobufData.SensorData)
          ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_SensorData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_SensorData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtobufDataOuterClass.ProtobufData.SensorData.class, ProtobufDataOuterClass.ProtobufData.SensorData.Builder.class);
        }

        // Construct using self.data.format.ProtobufDataOuterClass.ProtobufData.SensorData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          sensor_ = 1;
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          x_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          y_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          z_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_SensorData_descriptor;
        }

        public ProtobufDataOuterClass.ProtobufData.SensorData getDefaultInstanceForType() {
          return ProtobufDataOuterClass.ProtobufData.SensorData.getDefaultInstance();
        }

        public ProtobufDataOuterClass.ProtobufData.SensorData build() {
          ProtobufDataOuterClass.ProtobufData.SensorData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtobufDataOuterClass.ProtobufData.SensorData buildPartial() {
          ProtobufDataOuterClass.ProtobufData.SensorData result = new ProtobufDataOuterClass.ProtobufData.SensorData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.sensor_ = sensor_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            timestamp_ = java.util.Collections.unmodifiableList(timestamp_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.timestamp_ = timestamp_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            x_ = java.util.Collections.unmodifiableList(x_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.x_ = x_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            y_ = java.util.Collections.unmodifiableList(y_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.y_ = y_;
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            z_ = java.util.Collections.unmodifiableList(z_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.z_ = z_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtobufDataOuterClass.ProtobufData.SensorData) {
            return mergeFrom((ProtobufDataOuterClass.ProtobufData.SensorData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtobufDataOuterClass.ProtobufData.SensorData other) {
          if (other == ProtobufDataOuterClass.ProtobufData.SensorData.getDefaultInstance()) return this;
          if (other.hasSensor()) {
            setSensor(other.getSensor());
          }
          if (!other.timestamp_.isEmpty()) {
            if (timestamp_.isEmpty()) {
              timestamp_ = other.timestamp_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTimestampIsMutable();
              timestamp_.addAll(other.timestamp_);
            }
            onChanged();
          }
          if (!other.x_.isEmpty()) {
            if (x_.isEmpty()) {
              x_ = other.x_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureXIsMutable();
              x_.addAll(other.x_);
            }
            onChanged();
          }
          if (!other.y_.isEmpty()) {
            if (y_.isEmpty()) {
              y_ = other.y_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureYIsMutable();
              y_.addAll(other.y_);
            }
            onChanged();
          }
          if (!other.z_.isEmpty()) {
            if (z_.isEmpty()) {
              z_ = other.z_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureZIsMutable();
              z_.addAll(other.z_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasSensor()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtobufDataOuterClass.ProtobufData.SensorData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtobufDataOuterClass.ProtobufData.SensorData) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int sensor_ = 1;
        /**
         * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
         */
        public boolean hasSensor() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
         */
        public ProtobufDataOuterClass.ProtobufData.Sensor getSensor() {
          ProtobufDataOuterClass.ProtobufData.Sensor result = ProtobufDataOuterClass.ProtobufData.Sensor.valueOf(sensor_);
          return result == null ? ProtobufDataOuterClass.ProtobufData.Sensor.ACCELERATION : result;
        }
        /**
         * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
         */
        public Builder setSensor(ProtobufDataOuterClass.ProtobufData.Sensor value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          sensor_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .self.data.format.ProtobufData.Sensor sensor = 1;</code>
         */
        public Builder clearSensor() {
          bitField0_ = (bitField0_ & ~0x00000001);
          sensor_ = 1;
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Long> timestamp_ = java.util.Collections.emptyList();
        private void ensureTimestampIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            timestamp_ = new java.util.ArrayList<java.lang.Long>(timestamp_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public java.util.List<java.lang.Long>
            getTimestampList() {
          return java.util.Collections.unmodifiableList(timestamp_);
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public int getTimestampCount() {
          return timestamp_.size();
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public long getTimestamp(int index) {
          return timestamp_.get(index);
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public Builder setTimestamp(
            int index, long value) {
          ensureTimestampIsMutable();
          timestamp_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public Builder addTimestamp(long value) {
          ensureTimestampIsMutable();
          timestamp_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public Builder addAllTimestamp(
            java.lang.Iterable<? extends java.lang.Long> values) {
          ensureTimestampIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, timestamp_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int64 timestamp = 2;</code>
         */
        public Builder clearTimestamp() {
          timestamp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Double> x_ = java.util.Collections.emptyList();
        private void ensureXIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            x_ = new java.util.ArrayList<java.lang.Double>(x_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public java.util.List<java.lang.Double>
            getXList() {
          return java.util.Collections.unmodifiableList(x_);
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public int getXCount() {
          return x_.size();
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public double getX(int index) {
          return x_.get(index);
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public Builder setX(
            int index, double value) {
          ensureXIsMutable();
          x_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public Builder addX(double value) {
          ensureXIsMutable();
          x_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public Builder addAllX(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureXIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, x_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double x = 3;</code>
         */
        public Builder clearX() {
          x_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Double> y_ = java.util.Collections.emptyList();
        private void ensureYIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            y_ = new java.util.ArrayList<java.lang.Double>(y_);
            bitField0_ |= 0x00000008;
           }
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public java.util.List<java.lang.Double>
            getYList() {
          return java.util.Collections.unmodifiableList(y_);
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public int getYCount() {
          return y_.size();
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public double getY(int index) {
          return y_.get(index);
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public Builder setY(
            int index, double value) {
          ensureYIsMutable();
          y_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public Builder addY(double value) {
          ensureYIsMutable();
          y_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public Builder addAllY(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureYIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, y_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double y = 4;</code>
         */
        public Builder clearY() {
          y_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Double> z_ = java.util.Collections.emptyList();
        private void ensureZIsMutable() {
          if (!((bitField0_ & 0x00000010) == 0x00000010)) {
            z_ = new java.util.ArrayList<java.lang.Double>(z_);
            bitField0_ |= 0x00000010;
           }
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public java.util.List<java.lang.Double>
            getZList() {
          return java.util.Collections.unmodifiableList(z_);
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public int getZCount() {
          return z_.size();
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public double getZ(int index) {
          return z_.get(index);
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public Builder setZ(
            int index, double value) {
          ensureZIsMutable();
          z_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public Builder addZ(double value) {
          ensureZIsMutable();
          z_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public Builder addAllZ(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureZIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, z_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double z = 5;</code>
         */
        public Builder clearZ() {
          z_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:self.data.format.ProtobufData.SensorData)
      }

      // @@protoc_insertion_point(class_scope:self.data.format.ProtobufData.SensorData)
      private static final ProtobufDataOuterClass.ProtobufData.SensorData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtobufDataOuterClass.ProtobufData.SensorData();
      }

      public static ProtobufDataOuterClass.ProtobufData.SensorData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<SensorData>
          PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
        public SensorData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new SensorData(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<SensorData> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SensorData> getParserForType() {
        return PARSER;
      }

      public ProtobufDataOuterClass.ProtobufData.SensorData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
     */
    public ProtobufDataOuterClass.ProtobufData.Type getType() {
      ProtobufDataOuterClass.ProtobufData.Type result = ProtobufDataOuterClass.ProtobufData.Type.valueOf(type_);
      return result == null ? ProtobufDataOuterClass.ProtobufData.Type.PING : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
     */
    public ProtobufDataOuterClass.ProtobufData.State getState() {
      ProtobufDataOuterClass.ProtobufData.State result = ProtobufDataOuterClass.ProtobufData.State.valueOf(state_);
      return result == null ? ProtobufDataOuterClass.ProtobufData.State.SUCCESS : result;
    }

    public static final int UID_FIELD_NUMBER = 4;
    private volatile java.lang.Object uid_;
    /**
     * <code>optional string uid = 4;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string uid = 4;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIST_FIELD_NUMBER = 5;
    private java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData> list_;
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    public java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData> getListList() {
      return list_;
    }
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    public java.util.List<? extends ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder>
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    public ProtobufDataOuterClass.ProtobufData.SensorData getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
     */
    public ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(2, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uid_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(5, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uid_);
      }
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtobufDataOuterClass.ProtobufData)) {
        return super.equals(obj);
      }
      ProtobufDataOuterClass.ProtobufData other = (ProtobufDataOuterClass.ProtobufData) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && state_ == other.state_;
      }
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && getListList()
          .equals(other.getListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtobufDataOuterClass.ProtobufData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtobufDataOuterClass.ProtobufData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtobufDataOuterClass.ProtobufData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtobufDataOuterClass.ProtobufData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code self.data.format.ProtobufData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:self.data.format.ProtobufData)
        ProtobufDataOuterClass.ProtobufDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufDataOuterClass.ProtobufData.class, ProtobufDataOuterClass.ProtobufData.Builder.class);
      }

      // Construct using self.data.format.ProtobufDataOuterClass.ProtobufData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufDataOuterClass.internal_static_self_data_format_ProtobufData_descriptor;
      }

      public ProtobufDataOuterClass.ProtobufData getDefaultInstanceForType() {
        return ProtobufDataOuterClass.ProtobufData.getDefaultInstance();
      }

      public ProtobufDataOuterClass.ProtobufData build() {
        ProtobufDataOuterClass.ProtobufData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufDataOuterClass.ProtobufData buildPartial() {
        ProtobufDataOuterClass.ProtobufData result = new ProtobufDataOuterClass.ProtobufData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uid_ = uid_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufDataOuterClass.ProtobufData) {
          return mergeFrom((ProtobufDataOuterClass.ProtobufData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufDataOuterClass.ProtobufData other) {
        if (other == ProtobufDataOuterClass.ProtobufData.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasUid()) {
          bitField0_ |= 0x00000008;
          uid_ = other.uid_;
          onChanged();
        }
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000010);
              listBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufDataOuterClass.ProtobufData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufDataOuterClass.ProtobufData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.Type getType() {
        ProtobufDataOuterClass.ProtobufData.Type result = ProtobufDataOuterClass.ProtobufData.Type.valueOf(type_);
        return result == null ? ProtobufDataOuterClass.ProtobufData.Type.PING : result;
      }
      /**
       * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
       */
      public Builder setType(ProtobufDataOuterClass.ProtobufData.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .self.data.format.ProtobufData.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int state_ = 1;
      /**
       * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.State getState() {
        ProtobufDataOuterClass.ProtobufData.State result = ProtobufDataOuterClass.ProtobufData.State.valueOf(state_);
        return result == null ? ProtobufDataOuterClass.ProtobufData.State.SUCCESS : result;
      }
      /**
       * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
       */
      public Builder setState(ProtobufDataOuterClass.ProtobufData.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .self.data.format.ProtobufData.State state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>optional string uid = 4;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string uid = 4;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uid = 4;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 4;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 4;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uid_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          list_ = new java.util.ArrayList<ProtobufDataOuterClass.ProtobufData.SensorData>(list_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtobufDataOuterClass.ProtobufData.SensorData, ProtobufDataOuterClass.ProtobufData.SensorData.Builder, ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder> listBuilder_;

      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.SensorData getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder setList(
          int index, ProtobufDataOuterClass.ProtobufData.SensorData value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder setList(
          int index, ProtobufDataOuterClass.ProtobufData.SensorData.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder addList(ProtobufDataOuterClass.ProtobufData.SensorData value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder addList(
          int index, ProtobufDataOuterClass.ProtobufData.SensorData value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder addList(
          ProtobufDataOuterClass.ProtobufData.SensorData.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder addList(
          int index, ProtobufDataOuterClass.ProtobufData.SensorData.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends ProtobufDataOuterClass.ProtobufData.SensorData> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.SensorData.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public java.util.List<? extends ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder>
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.SensorData.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            ProtobufDataOuterClass.ProtobufData.SensorData.getDefaultInstance());
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public ProtobufDataOuterClass.ProtobufData.SensorData.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, ProtobufDataOuterClass.ProtobufData.SensorData.getDefaultInstance());
      }
      /**
       * <code>repeated .self.data.format.ProtobufData.SensorData list = 5;</code>
       */
      public java.util.List<ProtobufDataOuterClass.ProtobufData.SensorData.Builder>
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtobufDataOuterClass.ProtobufData.SensorData, ProtobufDataOuterClass.ProtobufData.SensorData.Builder, ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder>
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtobufDataOuterClass.ProtobufData.SensorData, ProtobufDataOuterClass.ProtobufData.SensorData.Builder, ProtobufDataOuterClass.ProtobufData.SensorDataOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:self.data.format.ProtobufData)
    }

    // @@protoc_insertion_point(class_scope:self.data.format.ProtobufData)
    private static final ProtobufDataOuterClass.ProtobufData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtobufDataOuterClass.ProtobufData();
    }

    public static ProtobufDataOuterClass.ProtobufData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtobufData>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufData>() {
      public ProtobufData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtobufData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufData> getParserForType() {
      return PARSER;
    }

    public ProtobufDataOuterClass.ProtobufData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_self_data_format_ProtobufData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_self_data_format_ProtobufData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_self_data_format_ProtobufData_SensorData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_self_data_format_ProtobufData_SensorData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#self.data.format/ProtobufData.proto\022\020s" +
      "elf.data.format\"\215\004\n\014ProtobufData\0221\n\004type" +
      "\030\001 \002(\0162#.self.data.format.ProtobufData.T" +
      "ype\022\021\n\ttimestamp\030\003 \002(\003\0223\n\005state\030\002 \001(\0162$." +
      "self.data.format.ProtobufData.State\022\013\n\003u" +
      "id\030\004 \001(\t\0227\n\004list\030\005 \003(\0132).self.data.forma" +
      "t.ProtobufData.SensorData\032w\n\nSensorData\022" +
      "5\n\006sensor\030\001 \002(\0162%.self.data.format.Proto" +
      "bufData.Sensor\022\021\n\ttimestamp\030\002 \003(\003\022\t\n\001x\030\003" +
      " \003(\001\022\t\n\001y\030\004 \003(\001\022\t\n\001z\030\005 \003(\001\"n\n\004Type\022\010\n\004PI",
      "NG\020\001\022\010\n\004PONG\020\002\022\n\n\006UPLOAD\020\003\022\016\n\nRSP_UPLOAD" +
      "\020\004\022\n\n\006SIGNUP\020\005\022\016\n\nRSP_SIGNUP\020\006\022\n\n\006SIGNIN" +
      "\020\007\022\016\n\nRSP_SIGNIN\020\010\"(\n\005State\022\013\n\007SUCCESS\020\001" +
      "\022\022\n\005ERROR\020\377\377\377\377\377\377\377\377\377\001\")\n\006Sensor\022\020\n\014ACCELE" +
      "RATION\020\001\022\r\n\tMAGNETISM\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_self_data_format_ProtobufData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_self_data_format_ProtobufData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_self_data_format_ProtobufData_descriptor,
        new java.lang.String[] { "Type", "Timestamp", "State", "Uid", "List", });
    internal_static_self_data_format_ProtobufData_SensorData_descriptor =
      internal_static_self_data_format_ProtobufData_descriptor.getNestedTypes().get(0);
    internal_static_self_data_format_ProtobufData_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_self_data_format_ProtobufData_SensorData_descriptor,
        new java.lang.String[] { "Sensor", "Timestamp", "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
