// automatically generated by the FlatBuffers compiler, do not modify

package self.data.format.flatbuffers;

public final class Sensor {
  private Sensor() { }
  public static final byte ACCELERATION = 1;
  public static final byte MAGNETISM = 2;

  public static final String[] names = { "ACCELERATION", "MAGNETISM", };

  public static String name(int e) { return names[e - ACCELERATION]; }
}

