// automatically generated by the FlatBuffers compiler, do not modify

package self.data.format.flatbuffers;

public final class State {
  private State() { }
  public static final byte ERROR = -1;
  public static final byte SUCCESS = 1;

  public static final String[] names = { "ERROR", "", "SUCCESS", };

  public static String name(int e) { return names[e - ERROR]; }
}

