// automatically generated by the FlatBuffers compiler, do not modify

package self.data.format.flatbuffers;

public final class Type {
  private Type() { }
  public static final byte PING = 1;
  public static final byte PONG = 2;
  public static final byte UPLOAD = 3;
  public static final byte RSP_UPLOAD = 4;
  public static final byte SIGNUP = 5;
  public static final byte RSP_SIGNUP = 6;
  public static final byte SIGNIN = 7;
  public static final byte RSP_SIGNIN = 8;

  public static final String[] names = { "PING", "PONG", "UPLOAD", "RSP_UPLOAD", "SIGNUP", "RSP_SIGNUP", "SIGNIN", "RSP_SIGNIN", };

  public static String name(int e) { return names[e - PING]; }
}

